
public static class T4Utils
{
    public delegate void WriteLineDelegate(string s, params object[] args);
    public static WriteLineDelegate WriteLine;

    public static void Comment(string s)
    {
        Print("//" + s);
    }

    public static void Print(string s, params object[] args)
    {
        if (WriteLine != null)
            WriteLine(s, args);
        else
            throw new System.Exception("T4Utils.WriteLine delegate must be assigned within the T4 template file!");
    }

    public static void FileHeader()
    {
        Print("/////////////////////////////////////////////////");
        Print("/// This file was autogenerated by a T4 template");
        //Print("///");
        //Print("/// Created: {0}", System.DateTime.Now);
        Print("///");
        Print("/// WARNING! All changes in this file will be lost!");
        Print("/////////////////////////////////////////////////");
        Print("");
    }

    public static string XmlHeader()
    {
        var b = new System.Text.StringBuilder();
        b.Append("This section was autogenerated by a T4 template  - ");
        //b.Append(string.Format("Last change: {0} - ", System.DateTime.Now));
        b.AppendLine("WARNING! All changes in this section will be lost!");
        return b.ToString();
    }
}